# Generated by Django 2.0.1 on 2018-01-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
