# Generated by Django 2.0.1 on 2018-01-30 07:58

from django.db import migrations, models
from datetime import date


def load_data(apps, schema_editor):
	PriceHistory = apps.get_model('historical_data', 'PriceHistory')

	PriceHistory(
		date=date(2013,11,29),
		price=1234.00,
		volume=354564,
		total_btc=12054345,
		).save()

	PriceHistory(
		date=date(2012,11,29),
		price=12.00,
		volume=35424,
		total_btc=12054000,
		).save()




class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_auto_20180130_0748'),
    ]

    operations = [
    	migrations.RunPython(load_data)
    ]
